# Generated by Django 2.2.1 on 2020-08-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parsed_url", models.URLField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("site_name", models.CharField(blank=True, max_length=255)),
                ("image_url", models.URLField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
